print('=========================================')
print('    SISTEMA DE FACTURACIÓN VETERINARIA    ')
print('=========================================')
nombre_dueno = input('Nombre del propietario: ')
nombre_mascota = input('Nombre de la mascota: ')  
valor_consulta = float(input('Valor base de la consulta ($): '))
costo_medicamentos = float(input('Costo de medicamentos recetados ($): '))
costo_procedimientos = float(input('Costo de procedimientos adicionales ($): '))
subtotal = valor_consulta + costo_medicamentos + costo_procedimientos
iva = subtotal * 0.19
total_pagar = subtotal + iva
print('=========================================')
print('          FACTURA DE ATENCIÓN           ')
print('=========================================')
print('Propietario:', nombre_dueno)
print('Mascota:',  nombre_mascota)
print('-----------------------------------------')
print('Valor Consulta base: $',valor_consulta)
print('Medicamentos:    $',costo_medicamentos)
print('Procedimientos extra: $',costo_procedimientos)
print('-----------------------------------------')
print('Subtotal:  $',subtotal)
print('IVA (19%):    $',iva)
print('-----------------------------------------')
print('TOTAL A PAGAR: $',total_pagar)
print('=========================================')